# Generated by Django 3.2.25 on 2024-05-08 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='phot',
            new_name='photo',
        ),
    ]
