# Generated by Django 3.2.25 on 2024-05-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240515_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
