# Generated by Django 3.2.25 on 2024-05-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240515_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
